# Generated by Django 4.0.3 on 2022-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null='False')),
                ('particulars', models.TextField(max_length=256, null='False')),
                ('transDate', models.DateTimeField(null='False')),
                ('amount', models.FloatField(null='False')),
                ('image_file', models.FileField(blank='True', null='True', upload_to='')),
            ],
        ),
    ]
