# Generated by Django 4.0.3 on 2022-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='addBy',
            field=models.CharField(max_length=100, null='False'),
            preserve_default='False',
        ),
    ]
