# Generated by Django 4.0.3 on 2022-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_addby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank='False', null='False'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='particulars',
            field=models.TextField(blank='False', max_length=256, null='False'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank='False', max_length=100, null='False'),
        ),
    ]
